src/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'


urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_view, name='register'),
    path('verify-email/<uidb64>/<token>/', views.verify_email, name='verify_email'),
]

src/api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('posts/', views.RecentPostListAPIView.as_view()),
    path('user-posts/', views.UserPostListAPIView.as_view()),
    path('posts/<slug:slug>/', views.PostDetailAPIView.as_view()),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('social/', include('social_accounts.urls')),
    path('profile/', include('profiles.urls')),

    path('api/', include('api.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name='password_reset/reset_password.html'
    ), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset/reset_password_sent.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset/reset.html'
    ), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset/reset_password_complete.html'
    ), name='password_reset_complete'),

    path('', include('blog.urls')),

    path('silk/', include('silk.urls', namespace='silk'))
]

if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/social_accounts/urls.py
from django.urls import path
from . import views

app_name = 'socialaccounts'

urlpatterns = [
    path('oauth/<str:provider>/', views.oauth_login, name='oauth_login'),
    path('oauth/<str:provider>/callback/', views.oauth_callback, name='oauth_callback'),
]

src/accounts/models.py
import logging

from uuid import uuid4

from django.db import models
from django.contrib.auth.models import AbstractUser


logger = logging.getLogger(__name__)


class AppUser(AbstractUser):
    """
    AppUser model extends the AbstractUser model to include additional fields and functionality.
    """

    email_verified = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    id = models.UUIDField(default=uuid4, unique=True, editable=False, primary_key=True)

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ('-created',)
        indexes = [
            models.Index(fields=['username'], name='appuser_username_idx'),
        ]

    def __str__(self):
        return self.username
    
    def get_absolute_url(self):
        pass

src/accounts/forms.py
from django.forms import ValidationError

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, get_user_model

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit, Column

from core.utils import send_verify_email


User = get_user_model()


class LoginForm(AuthenticationForm):
    """
    A form for user authentication that extends the AuthenticationForm.
    This form uses crispy-forms to render the form fields with custom CSS classes
    and placeholders.
    """
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.layout = Layout(
            Column(
                Field('username', css_class='form-control rounded-3', placeholder='Username or Email', required=True),
                css_class='mb-3 text-start'
            ),
            Column(
                Field('password', css_class='form-control rounded-3', placeholder='Password', required=True),
                css_class='mb-3 text-start'
            ),
            Submit('submit', 'Sign In', css_class='btn btn-dark w-100 rounded-0 fw-semibold'),
        )


class RegisterForm(UserCreationForm):
    """
    A custom user registration form that extends the UserCreationForm.
    """

    class Meta:
        model = User
        fields = [
            'email', 'username', 'password1', 'password2'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.layout = Layout(
            Column(
                Field('email', css_class='form-control rounded-3', autofocus=True, placeholder='Email', required=True),
                css_class='mb-3 text-start'
            ),
            Column(
                Field('username', css_class='form-control rounded-3', placeholder='Username', required=True),
                css_class='mb-3 text-start'
            ),
            Column(
                Field('password1', css_class='form-control rounded-3', placeholder='Password', required=True),
                css_class='mb-3 text-start'
            ),
            Column(
                Field('password2', css_class='form-control rounded-3', placeholder='Repeat Password', required=True),
                css_class='mb-3 text-start'
            ),
            Submit('submit', 'Sign Up', css_class='btn btn-dark w-100 rounded-0 fw-semibold'),
        )

    def save(self, commit=True):
        user = super().save(commit=False)

        user.is_active = False

        if commit:
            user.save()
            send_verify_email(user)

        return user


    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            raise ValidationError('Email is already taken')
        
        return email

    def clean_username(self):
        username = self.cleaned_data.get('username').lower()

        if User.objects.filter(username=username).exists():
            raise ValidationError('Username is already taken')

        return username

src/accounts/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import login, get_user_model, logout
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib import messages

from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode

from .forms import LoginForm, RegisterForm


User = get_user_model()
token_generator = PasswordResetTokenGenerator()


def login_view(request):
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            if user is not None:
                login(request, user)
                messages.success(request, 'Logged In')
                return redirect('/')
    else:
        form = LoginForm()

    context = {
        'title': 'Sign In',
        'form': form,
    }

    return render(request, 'accounts/login.html', context)


def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
        messages.info(request, 'Signed Out')
    return redirect('/')


def register_view(request):
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return render(
                request,
                'emails/verify_email_sent.html',
                {'title': 'Email sent'}
            )
    else:
        form = RegisterForm()

    context = {
        'title': 'Sign Up',
        'form': form,
    }

    return render(request, 'accounts/register.html', context)


def verify_email(request, uidb64, token):
    if request.user.is_authenticated and request.user.email_verified:
        return redirect('/')

    user = None
    try:
        uid_bytes = urlsafe_base64_decode(force_str(uidb64))
        uid_str = uid_bytes.decode('utf-8')
        user = User.objects.get(pk=uid_str)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist, UnicodeDecodeError):
        user = None

    if user is not None and token_generator.check_token(user, token):
        user.is_active = True
        if hasattr(user, 'email_verified'):
            user.email_verified = True
        user.save()

        user.backend = 'django.contrib.auth.backends.ModelBackend'

        login(request, user)
        messages.success(request, 'Signed Up')
        return redirect('profiles:edit_profile')
    
    elif user and not user.email_verified:
        user.delete()

    return render(
        request,
        'emails/verify_email_failed.html',
        {'title': 'Email failed'}
    )

src/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
{{ title }}
{% endblock title %}

{% block content %}

<div class="d-flex justify-content-center align-items-center mt-5 mb-5">
    <div class="card shadow-lg p-4 border-0 rounded-0" style="width: 28rem;">
        <div class="card-body text-center">
            <h3 class="card-title mb-3 fw-bold">Login</h3>
            {% crispy form %}
            <p class="mt-3 text-muted">
                Forgot your password? <a href="{% url 'reset_password' %}" class="text-primary">Reset</a>
                <br>
                Don't have an account? <a href="{% url 'accounts:register' %}" class="text-primary">Sign Up</a>
            </p>
            
            <hr>
            
            <div class="text-center">
                <small class="text-muted">or sign up using:</small>
            </div>
            <div class="d-flex justify-content-center flex-wrap mb-3">
                <a href="{% url 'socialaccounts:oauth_login' 'google' %}" class="btn btn-outline-dark rounded-3 d-flex justify-content-center align-items-center me-2 mb-1">
                    <i class="bi bi-google me-1" style="font-size: 20px;"></i>
                    <span>Google</span>
                </a>
                <a href="{% url 'socialaccounts:oauth_login' 'github' %}" class="btn btn-outline-dark rounded-3 d-flex justify-content-center align-items-center me-2 mb-1">
                    <i class="bi bi-github me-1" style="font-size: 20px;"></i>
                    <span>GitHub</span>
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

src/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block content %}

<div class="d-flex justify-content-center align-items-center mt-5 mb-5">
    <div class="card shadow-lg p-4 border-0 rounded-0" style="width: 35rem;">
        <div class="card-body text-center">
            <h3 class="card-title mb-3 fw-bold">Sign Up</h3>
            {% crispy form %}
            <p class="mt-3 text-muted">Already have an account? <a href="{% url 'accounts:login' %}" class="text-primary">Sign In</a></p>
            
            <hr>
            
            <div class="text-center">
                <small class="text-muted">or sign up using:</small>
            </div>
            <div class="d-flex justify-content-center flex-wrap mb-3">
                <a href="{% url 'socialaccounts:oauth_login' 'google' %}" class="btn btn-outline-dark rounded-3 d-flex justify-content-center align-items-center me-2 mb-1">
                    <i class="bi bi-google me-1" style="font-size: 20px;"></i>
                    <span>Google</span>
                </a>
                <a href="{% url 'socialaccounts:oauth_login' 'github' %}" class="btn btn-outline-dark rounded-3 d-flex justify-content-center align-items-center me-2 mb-1">
                    <i class="bi bi-github me-1" style="font-size: 20px;"></i>
                    <span>GitHub</span>
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}