src/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'


urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_view, name='register'),
    path('verify-email/<uidb64>/<token>/', views.verify_email, name='verify_email'),
]

src/api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('posts/', views.RecentPostListAPIView.as_view()),
    path('user-posts/', views.UserPostListAPIView.as_view()),
    path('posts/<slug:slug>/', views.PostDetailAPIView.as_view()),
]

src/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.posts_list, name='posts_list'),
    path('get-posts/', views.get_posts, name='get_posts'),

    path('post/<str:slug>/', views.post_detail, name='post_detail'),
    path('create-post/', views.create_post, name='create_post'),
    path('edit-post/<str:slug>/', views.edit_post, name='edit_post'),
    path('delete-post/<str:slug>/', views.delete_post, name='delete_post'),

    path('create-comment/<str:slug>/', views.create_comment, name='create_comment'),
    path('upvote/<str:slug>/', views.upvote_post, name='upvote_post'),
    
    path('search/', views.search, name='search'),

    path('settings/', views.user_settings, name='settings'),
    path('publish-draft/', views.publish_draft, name='publish_draft'),

    path('tags/search/', views.tag_search, name='tag_search'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('social/', include('social_accounts.urls')),
    path('profile/', include('profiles.urls')),

    path('api/', include('api.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name='password_reset/reset_password.html'
    ), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset/reset_password_sent.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset/reset.html'
    ), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset/reset_password_complete.html'
    ), name='password_reset_complete'),

    path('', include('blog.urls')),

    path('silk/', include('silk.urls', namespace='silk'))
]

if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/includes/footer.html
<footer class="bg-white py-3 text-center border-top">
    <p class="mb-0 text-muted">© 2025 Django Blog</p>
</footer>

src/templates/includes/messages.html
{% if messages %}
    <div class="d-flex justify-content-center w-100 fixed-top" style="z-index: 1050; margin-top: 30px;">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} radius-md border-0 shadow-lg mt-2 alert-dismissible fade show text-center" role="alert"
                style="max-width: 300px;">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
{% endif %}

src/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom sticky-top">
    <div class="container d-flex align-items-center">
        <a class="navbar-brand fw-bold" href="/">Django Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <form class="d-flex me-auto my-2 my-lg-0" method="get" action="{% url 'blog:search' %}">
                <input class="form-control me-2 rounded-5" type="search" name="query" placeholder="Search posts..." aria-label="Search">
                <button class="btn btn-outline-dark btn-sm rounded-5" type="submit">Search</button>
            </form>
            <ul class="navbar-nav ms-auto d-lg-flex align-items-lg-center">
                {% if request.user.is_authenticated %}
                    <li class="nav-item me-3">
                        <a class="nav-link d-flex align-items-center" href="{% url 'blog:create_post' %}">
                            <i class="bi bi-feather me-1"></i> Write
                        </a>
                    </li>
                    <div class="dropdown nav-item">
                        <button class="btn dropdown-toggle nav-link d-flex align-items-center" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ request.user.profile.image.url|default:'/media/defaults/def.png' }}" alt="Img" class="rounded-circle" width="35" height="35">
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{% url 'blog:settings' %}">Settings</a>
                        </div>
                    </div>                    
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Sign In</a></li>
                    <li class="nav-item"><a class="nav-link btn btn-outline-light btn-sm" href="#">Get Started</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

src/templates/includes/pagination.html
{% if queryset.has_other_pages %}
    <nav aria-label="Page navigation" class="mt-4">
        <ul class="pagination justify-content-center">
            <li class="page-item {% if not queryset.has_previous %}disabled{% endif %}">
                <a class="page-link rounded-0 text-dark" 
                   href="{% if query %}?query={{ query }}&page=1{% else %}?page=1{% endif %}">
                   &#10094;&#10094;
                </a>
            </li>
            {% if queryset.has_previous %}
                <li class="page-item">
                    <a class="page-link rounded-0 text-dark" 
                       href="{% if query %}?query={{ query }}&page={{ queryset.previous_page_number }}{% else %}?page={{ queryset.previous_page_number }}{% endif %}">
                       &#10094;
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link rounded-0 text-dark">&#10094;</span>
                </li>
            {% endif %}
            {% for page in custom_range %}
                <li class="page-item {% if page == queryset.number %}active{% endif %}">
                    <a class="page-link {% if page == queryset.number %}bg-dark border-dark text-light{% endif %}" 
                       href="{% if query %}?query={{ query }}&page={{ page }}{% else %}?page={{ page }}{% endif %}">
                        {{ page }}
                    </a>
                </li>
            {% endfor %}
            {% if queryset.has_next %}
                <li class="page-item">
                    <a class="page-link rounded-0 text-dark" 
                       href="{% if query %}?query={{ query }}&page={{ queryset.next_page_number }}{% else %}?page={{ queryset.next_page_number }}{% endif %}">
                       &#10095
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link rounded-0 text-dark">&#10095;</span>
                </li>
            {% endif %}
            <li class="page-item {% if not queryset.has_next %}disabled{% endif %}">
                <a class="page-link rounded-0 text-dark" 
                   href="{% if query %}?query={{ query }}&page={{ num_pages }}{% else %}?page={{ num_pages }}{% endif %}">
                   &#10095;&#10095;
                </a>
            </li>
        </ul>
    </nav>
{% endif %}